<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Stat2</title>

<script src="site_libs/header-attrs-2.26/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Jihyun (Jenny) Seo</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="tutorials.html">Tutorials</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Stat/ML
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="stat1.html">Predicting Campaign Offer Acceptance</a>
    </li>
    <li>
      <a href="stat2.html">Statistics using R</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    DB/SQL
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="dbsql1.html">Movie Explorer</a>
    </li>
    <li>
      <a href="dbsql2.html">Movie Explorer2</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="visualization1.html">Squid Game Elimination Analysis</a>
    </li>
    <li>
      <a href="visualization2.html">Squid Game Elimination Analysis2</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="contact.html">
    <span class="fa fa-sharp fa-solid fa-envelope"></span>
     
  </a>
</li>
<li>
  <a href="files/RESUME_SEO JIHYUN.pdf">
    <span class="ai ai-cv ai-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/JennyJihyunSeo">
    <span class="fab fa-github"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/ssue513">
    <span class="fab fa-linkedin-in"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Statistics using R</h1>

</div>


<p><link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="site_libs/academicons-1.9.1/css/academicons.min.css"/></p>
<p><br><br><br></p>
<p><br><br><br></p>
<div id="hypothesis-testing-with-two-sample-proportion-test"
class="section level2">
<h2>1. Hypothesis Testing with Two-Sample Proportion Test</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<div id="figure" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/Lecture1.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. Treatment Effects between New banner Ad and Old Banner Ad]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="goal" class="section level3">
<h3>2. Goal</h3>
<p>To test if the Click-Through-Rate (CTR) difference between Ad B
(treatment group) and Ad A (Control group).</p>
<p><br></p>
</div>
<div id="hypotheses" class="section level3">
<h3>3. Hypotheses</h3>
<p><strong>Null Hypothesis (H₀):</strong> - The null hypothesis
indicates Ad B is not effective than Ad A - The null hypothesis
indicates the CTR (Click through Rate) of Ad B is less than or equal to
the CTR (Click through Rate) of Ad A <span class="math display">\[
H_0: p_B \leq p_A
\]</span></p>
<p><strong>Alternative Hypothesis (H₁):</strong> - The null hypothesis
indicates Ad B is more effective than Ad A - The null hypothesis
indicates the CTR (Click through Rate) of Ad B is more than the CTR of
Ad A <span class="math display">\[
H_1: p_B &gt; p_A
\]</span></p>
<p><br></p>
</div>
<div id="methodology-summary" class="section level3">
<h3>4. Methodology &amp; Summary</h3>
<ul>
<li>Two Sample proportion z-test was used:
<ul>
<li>Ad A and Ad B each had 500 samples.</li>
<li>Success = clicking the ad (CTR).</li>
<li>CTR of Ad A = 3% CTR and Ad B = 5.6% CTR.</li>
<li>Result: p-value = 0.0307 rejecting the null hypothesis.</li>
</ul></li>
<li>Conclusion: At a 0.05 significance level, the p-value of 0.0307
indicates that the null hypothesis (Ad B is not more effective than Ad
A) can be rejected. The p-value represents the probability of observing
a result as extreme as, or more extreme than, the current outcome under
the assumption that the null hypothesis is true. Since the p-value is
less than the significance level, we have sufficient evidence to reject
the null hypothesis, suggesting that Ad B is statistically significantly
more effective than Ad A.</li>
</ul>
<p><br></p>
</div>
<div id="code" class="section level3">
<h3>5. Code</h3>
<pre class="r"><code>#Q1
### Set seed to ensure we consistently generate the same results
set.seed(1)

### Create two random samples of A and B with sample size 500 respectively 
### A and B are distributed binomial with sample means 0.03 and 0.05
### A and B follow binomial distributions while indicating 1 is success (clicking the Ad) and 0 is failure (not clicking the Ad)
nbin &lt;- 500
A &lt;- data.frame(CTR = rbinom(n = nbin, prob = 0.03, size = 1))
B &lt;- data.frame(CTR = rbinom(n = nbin, prob = 0.05, size = 1))

### Sample counts, counting the success of clicking the Ad.
countA &lt;- sum(A$CTR)
countB &lt;- sum(B$CTR)

### Two-sample proportions z-test with one-sided test 
prop.test(x = c(countB, countA), 
          n = c(nbin, nbin), 
          alternative = &quot;greater&quot;)</code></pre>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(countB, countA) out of c(nbin, nbin)
## X-squared = 3.4993, df = 1, p-value = 0.0307
## alternative hypothesis: greater
## 95 percent confidence interval:
##  0.00294022 1.00000000
## sample estimates:
## prop 1 prop 2 
##  0.056  0.030</code></pre>
<pre class="r"><code># Ad B is clicked 5% otherwise Ad A is clicked 3% on the time but this is very unlikely (only 3% based on the p-value) that 
# this outcome can be gained under the assumption that the null hypothesis is true. Therefore, we suspect that the null hypothesis is not true.</code></pre>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="hypothesis-testing-with-10000-random-samples"
class="section level2">
<h2>2. Hypothesis Testing with 10,000 Random Samples</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="figure-1" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/Lecture1.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. Treatment Effects between New banner Ad and Old Banner Ad]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="goal-1" class="section level3">
<h3>2. Goal</h3>
<p>To test if the mean Click-Through-Rate (CTR) between Ad A and Ad B is
greater than 2.6%.</p>
<p><br></p>
</div>
<div id="hypotheses-1" class="section level3">
<h3>3. Hypotheses</h3>
<p><strong>Null Hypothesis (H₀):</strong></p>
<p>The mean difference in CTR between Ad B and Ad A is <strong>less than
or equal to 2.6%</strong>:</p>
<p><span class="math display">\[
H_0: \mu_B - \mu_A \leq 0.026
\]</span></p>
<p><strong>Alternative Hypothesis (H₁):</strong></p>
<p>The mean difference in CTR between Ad B and Ad A is <strong>greater
than 2.6%</strong>:</p>
<p><span class="math display">\[
H_1: \mu_B - \mu_A &gt; 0.026
\]</span></p>
<p><br></p>
</div>
<div id="methodology-summary-1" class="section level3">
<h3>4. Methodology &amp; Summary</h3>
<ul>
<li>Two Sample proportion z-test was used:
<ul>
<li>10,000 random samples of size 500 were drawn for both Ad A and Ad B,
assuming both had a mean CTR of 4.3%, which indicates that those samples
are simulated under the assumption that the null hypothesis is true as
the mean of each distribution is the same as each other.</li>
<li>The mean CTR difference was calculated.</li>
<li>If the mean difference exceeded 2.6%, the null hypothesis was
rejected.</li>
<li>Result: p-value = 0.0242 rejecting the null hypothesis.</li>
</ul></li>
<li>Conclusion: At a 0.05 significance level, the p-value of 0.0242
indicates that the null hypothesis (The mean difference between the two
Ads is less than or equal to 2.6%.) can be rejected. The p-value
represents the probability of observing a difference as extreme as, or
more extreme than, 2.6% under the assumption that the null hypothesis is
true. The probability of observing this extreme value (the mean
difference between the two Ads greater than 2.6%) is 2.4%. Since the
p-value is less than the significance level, we have sufficient evidence
to reject the null hypothesis, suggesting that Ad B is statistically
significantly 2.6% more effective than Ad A.</li>
</ul>
<p><br></p>
</div>
<div id="code-1" class="section level3">
<h3>5. Code</h3>
<pre class="r"><code>### 10,000 random samples from binomial with mean 0.043, for both Ad A and AD B which fits the null hypothesis with Ad B not being more effective than Ad A
### 4.3% indicates the average CTR of A and B 
### The purpose for this sampling is to identify whether CTR for Ad B is 2.6% larger than Ad A even if we got random samples for binomial distribution with the same average mean for both Ad A and Ad B. 

set.seed(1)
### Create data frame for mean of samples 
hypothesis &lt;- data.frame(matrix(0, nrow = 10000, ncol = 4))

### Name columns 
colnames(hypothesis) &lt;- c(&#39;A&#39;, &#39;B&#39;, &#39;Dif&#39;, &#39;RejectH0&#39;)

for (x in 1:10000) {
  # The sample mean is the same as 4.3% (CTR = 4.3%)
  hypothesis$A[x] &lt;- mean(rbinom(n = nbin, prob = 0.043, size = 1))
  hypothesis$B[x] &lt;- mean(rbinom(n = nbin, prob = 0.043, size = 1))
  
  # The difference in CTR between A and B
  hypothesis$Dif[x] &lt;- hypothesis$B[x] - hypothesis$A[x]
  
  # If the CTR of B is greater than 2.6% than A, we reject the null hypothesis.
  hypothesis$RejectH0[x] &lt;- ifelse(hypothesis$B[x] - hypothesis$A[x] &gt; 0.026, 1, 0)
}

# The summary table of the result for this hypothesis testing.
summary(hypothesis$RejectH0)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  0.0000  0.0242  0.0000  1.0000</code></pre>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="random-sampling" class="section level2">
<h2>3. Random Sampling</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="figure-2" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/RandomSampling.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. How Sample Mean Evolves as Sample Size Increases]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="goal-2" class="section level3">
<h3>2. Goal</h3>
<ul>
<li>To demonstrate how the sample mean evolves as the sample size
increases, and how the population variance affects the variability of
sample means.
<ul>
<li>The sample mean becomes closer to the true population mean as the
sample size increases.</li>
<li>The stability of sample means improves when sampling from
populations with lower variance.</li>
</ul></li>
</ul>
<p><br></p>
</div>
<div id="methodology" class="section level3">
<h3>3. Methodology</h3>
<ol style="list-style-type: decimal">
<li>Setup:
<ul>
<li>Two populations are sampled, both with a mean of 70 but with
different variances.
<ul>
<li>Population 1: Variance = 36 (Standard Deviation = 6)</li>
<li>Population 2: Variance = 9 (Standard Deviation = 3)</li>
</ul></li>
<li>Sample sizes range from 1 to 100.</li>
</ul></li>
<li>Process:
<ul>
<li>Random samples are drawn from each population for each sample size
(1 to 100).</li>
<li>The sample means are calculated and stored for both
populations.</li>
</ul></li>
<li>Process:
<ul>
<li>The sample means are plotted against sample sizes to observe
trends.</li>
<li>Red Line: Population with larger variance (36)</li>
<li>Blue Line: Population with smaller variance (9)</li>
</ul></li>
<li>Conclusion:
<ul>
<li>When the population variance is larger and sampling from this
population, the sample means vary largely when the sample size is
smaller. This variance is getting smaller when the sample size
increases. In contrast, if the population variance is smaller and random
samples from this population, there is less variability in the sample
means compared to the first random sampling from the population with
larger variance. The sample mean of the second population gets closer to
the population mean which is 70 rapidly while showing greater stability
even when the sample size is small.</li>
</ul></li>
</ol>
<p><br></p>
</div>
<div id="code-2" class="section level3">
<h3>4. Code</h3>
<pre class="r"><code>### Set seed to ensure we consistently generate the same results 
set.seed(1)

### Create data frame to store the means of the samples
sample_example &lt;- data.frame(matrix(0, nrow = 100, ncol = 3))

### Name columns
colnames(sample_example) &lt;- c(&#39;ssize&#39;, &#39;mean1&#39;, &#39;mean2&#39;)

# Create random samples from a normal distribution with mean = 70 but with different variance
# Sample sizes range from 1 to 100

for (x in 1:100) {
  # Generate random samples for two sets from the normal distribution with the same mean 70 and different variances. The first sample has 70 as mean and 36 as variance. The second sample has 70 as mean and 9 as variance. 
  sample_run1 &lt;- data.frame(sample = rnorm(x, 70, 36))
  sample_run2 &lt;- data.frame(sample = rnorm(x, 70, 9))
  
  # Store the sample size
  sample_example$ssize[x] &lt;- x
  
  # Calculate the means of the samples and store them 
  sample_example$mean1[x] &lt;- mean(sample_run1$sample)
  sample_example$mean2[x] &lt;- mean(sample_run2$sample)
}

# View the results
head(sample_example)</code></pre>
<pre><code>##   ssize    mean1    mean2
## 1     1 47.44766 71.65279
## 2     2 83.67374 67.79068
## 3     3 91.61842 74.78871
## 4     4 54.19651 75.27123
## 5     5 72.92430 66.86281
## 6     6 68.78623 71.48757</code></pre>
<pre class="r"><code># When the sample size is the same in each row, if the standard deviation is smaller, we could get more stable sample means closer to the population mean 70.</code></pre>
<pre class="r"><code>### Plot X=Sample Size, Y = mean
library(ggplot2)
ggplot() + 
  geom_line(data=sample_example, aes(x=ssize,y=mean1), color=&quot;red&quot;)+ 
  geom_line(data=sample_example, aes(x=ssize,y=mean2), color=&quot;blue&quot;)+ 
  ggtitle(&quot;How sample mean evolves as sample size increases&quot;) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x=&#39;Sample Size&#39;,y=&#39;Sample Mean&#39;)</code></pre>
<p><img src="stat2_files/figure-html/unnamed-chunk-4-1.png" width="672" />
<br></p>
<p><br><br><br></p>
</div>
</div>
<div id="multi-armed-bandit" class="section level2">
<h2>4. Multi-Armed Bandit</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="definition" class="section level3">
<h3>1. Definition</h3>
<ul>
<li>The Multi-Armed Bandit approach tests multiple levers (e.g.,
advertisements) to identify the best lever offering the highest
compensation. In this case:
<ul>
<li>4 advertisements are tested to determine the one with the highest
CTR (Click-Through Rate).</li>
<li>Fisher’s exact test is used instead of the proportion test when
sample sizes (exposures of advertisements) are low.</li>
</ul></li>
</ul>
<p><br></p>
<p><br><br></p>
</div>
<div id="goal-3" class="section level3">
<h3>2. Goal</h3>
<p>To identify the advertisement with the highest CTR and evaluate
whether any other advertisements can serve as suitable alternatives.</p>
<p><br></p>
</div>
<div id="methodology-1" class="section level3">
<h3>3. Methodology</h3>
<ol style="list-style-type: decimal">
<li>Setup:
<ul>
<li>Four advertisements (Ad1, Ad2, Ad3, Ad4) are initialized with
baseline CTRs:
<ul>
<li>Ad1: 2.5%, Ad2: 1%, Ad3: 0.5%, Ad4: 1.5%.</li>
</ul></li>
<li>The best advertisement starts with the highest baseline CTR.</li>
</ul></li>
<li>Dynamic Sampling:
<ul>
<li>Advertisements are exposed probabilistically, with higher
probabilities assigned to the current best-performing ad.</li>
<li>A random click (1 for success, 0 for failure) is generated based on
the CTR of the selected ad.</li>
</ul></li>
<li>Updating Beliefs:
<ul>
<li>Clicks and exposures are updated after each trial.</li>
<li>CTR for each advertisement is recalculated:
<ul>
<li><strong>CTR</strong> (Click-Through Rate):</li>
</ul></li>
</ul></li>
</ol>
<p><span class="math display">\[
\text{CTR} = \frac{\text{Clicks}}{\text{Exposures}}
\]</span> + CTR represents the ratio of the number of clicks to the
number of times an advertisement was shown (exposures).</p>
<ol start="4" style="list-style-type: decimal">
<li>Testing Significance:
<ul>
<li>Once all advertisements have at least 10 exposures, Fisher’s test is
applied:</li>
<li><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>):</strong></li>
</ul>
<span class="math display">\[
H_0: \text{CTR}_{\text{Best}} \geq \text{CTR}_{\text{Alternative}}
\]</span>
<ul>
<li><strong>Alternative Hypothesis (<span
class="math inline">\(H_1\)</span>):</strong></li>
</ul>
<span class="math display">\[
H_1: \text{CTR}_{\text{Best}} &lt; \text{CTR}_{\text{Alternative}}
\]</span>
<ul>
<li>Advertisements with p-values &lt; 0.05 are removed due to
significant differences from the best ad.</li>
</ul></li>
<li>Conclusion:
<ul>
<li>The process continues until only the best advertisement and its
close alternatives (if any) remain.</li>
<li>The first advertisement has the highest CTR and there are no
suitable alternatives with similar CTR compared to the best choice.</li>
</ul></li>
</ol>
<p><br></p>
</div>
<div id="code-3" class="section level3">
<h3>4. Code</h3>
<pre class="r"><code># Choose 4 advertisements 
N_ARMS = 4
# Identifier for each advertisement 
ARMS = c(1,2,3,4)
# Set the baseline CTR for each advertisement 
base_rates = c(.025,.01,.005,.015)
# Before the experiment, the first advertisement has the highest CTR
best = 1
# Initialize the number of clicks, the number of advertisement exposure, and CTR (the number of clicks / the total number of advertisement exposure)
clicks &lt;-c(0,0,0,0)
draws &lt;-c(0,0,0,0)
CTR &lt;-c(0,0,0,0)

options(warn=-1)

set.seed(1)

while(N_ARMS&gt;1){
  # Generate a random draw of ad from proportion .5 best, else other)
  # Set arm probabilities
  # Except for the best advertisement, 0.5 probabilities divided by remaining advertisements
  epsilon = .5/(N_ARMS-1)
  chosen_arm_p = c(0,0,0,0)
  for (i in 1:length(ARMS)) {
    chosen_arm_p[ARMS[i]]=epsilon
  }
  # Assign 0.5 exposure probability for the best advertisement
  chosen_arm_p[best]=.5
  # Choose the probability as the threshold to pull the arm
  choicep &lt;- runif(1, min = 0, max = 1)
  choice=0
  # Choose the advertisement when the choice probability generated by uniform distribution is included in the cumulative range for each advertisement
  # If one of the advertisements is selected, choice == 0 is not satisfied and the for loop is ended. 
  for (i in 1:length(ARMS)) {
    if (choicep&lt;=sum(chosen_arm_p[1:ARMS[i]]) &amp; choice==0){choice=ARMS[i]}
  }
  # Generate click or not click using CTR for each advertisement set above
  # click has 1 (click) or 0 (not click) for one exposure 
  click &lt;- rbinom(n=1,prob=base_rates[choice],size=1)
  # Update beliefs about frequency
  # Accumulate the number of clicks for each advertisement 
  clicks[choice] &lt;- clicks[choice]+click
  # The number of exposure increments by 1 for every trial 
  draws[choice] &lt;- draws[choice]+1
  # If the exposure is 0, the value is returned as 0 whereas CTR is calculated as clicks[choice] / draws [choice]
  CTR[choice] = ifelse(draws[choice]==0, 0, (clicks[choice]/draws[choice]))
  # Re-assign best 
  best=0
  # CTR object stores the CTR for each advertisement and find the best advertisement with the max CTR value
  for (i in 1:length(ARMS)) {
    if (CTR[ARMS[i]]==max(CTR) &amp; best==0){best=ARMS[i]}
  }
  # Test for significant difference between the best advertisement and the rest of the options
  # Remove all for which p-value &lt;0.05, indicating that there is significant difference between the best and other option
  # Only remove once each alternative has been drawn at least ten times 
  # prop.test inappropriate and gives error if samples are too small
  # The minimum exposure for each advertisement is greater than 10
  if (min(draws)&gt;10) {
  keep = c()
  for (i in 1:length(ARMS)) {
    if (ARMS[i]!=best) {
      # The null hypothesis for the prop.test is CTR(best) is greater or than or equal to CTR(alternative) and the alternative hypothesis is CTR(best) is less than CTR(alternative). 
      # If the null hypothesis is rejected, that alternative should be removed because there is statistically significant difference between the two. However, in this example. prop.test cannot be used due to lower exposure. Chi-squared test may not be appropriate when numerator is zero or very low.
      # Fisher&#39;s test should be used 
    result&lt;-fresult &lt;- fisher.test(
  matrix(
    c(clicks[best], clicks[ARMS[i]], 
      draws[best] - clicks[best], draws[ARMS[i]] - clicks[ARMS[i]]),
    nrow = 2
  ),
  alternative = &quot;greater&quot;
)
    if (result$p.value&gt;.05) {keep=c(keep,ARMS[i])}
    }
    if (ARMS[i]==best) {keep = c(keep,best)}
  }
  N_ARMS = length(keep)
  ARMS=keep
  }
}

ARMS  </code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>rbind(base_rates, CTR)</code></pre>
<pre><code>##                  [,1] [,2]        [,3]      [,4]
## base_rates 0.02500000 0.01 0.005000000 0.0150000
## CTR        0.02311007 0.00 0.003984064 0.0158883</code></pre>
<pre class="r"><code>draws</code></pre>
<pre><code>## [1] 2553  151  251 2077</code></pre>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="instagram-ads-ab-testing-disney" class="section level2">
<h2>5. Instagram Ads A/B Testing (Disney)</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="figure-3" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/Disney.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. Decide whether to continue on the Ad based on Incremental
Conversion Rate]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="goal-4" class="section level3">
<h3>2. Goal</h3>
<p>To identify whether any treatment effect represented by Incremental
Conversion Rate (ICR) is positive.</p>
<p><br></p>
</div>
<div id="hypotheses-and-formula-of-icr" class="section level3">
<h3>3. Hypotheses and Formula of ICR</h3>
<ul>
<li><p>The <strong>Incremental Conversion Rate (ICR)</strong> is defined
as:</p>
<ul>
<li><strong>ICR</strong> (Incremental Conversion Rate):</li>
</ul>
<p><span class="math display">\[
\text{ICR} = \text{Conversion_Rate(Treatment)} -
\text{Conversion_Rate(Control)}
\]</span></p></li>
<li><p><strong>Treatment group</strong>: Exposed to the
advertisement.<br />
</p></li>
<li><p><strong>Control group</strong>: Not exposed to the
advertisement.</p></li>
<li><p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>):</strong></p>
<p><span class="math display">\[
H_0: \text{ICR} \leq 0 \quad \text{(The incremental conversion rate is
less than or equal to 0)}.
\]</span></p></li>
<li><p><strong>Alternative Hypothesis (<span
class="math inline">\(H_1\)</span>):</strong></p>
<p><span class="math display">\[
H_1: \text{ICR} &gt; 0 \quad \text{(The incremental conversion rate is
greater than 0)}.
\]</span></p></li>
</ul>
</div>
<div id="conclusion" class="section level3">
<h3>4. Conclusion:</h3>
<ul>
<li>The p-value obtained from this test allow us to reject the null
hypothesis. This indicates that the conversion rate in the treatment
group is statistically significantly greater than that in the control
group.</li>
</ul>
<p><br></p>
</div>
<div id="code-4" class="section level3">
<h3>5. Code</h3>
<pre class="r"><code># Load the RData file
load(&quot;DisneyAB.Rdata&quot;) 
### tests
### Proportion test for ICR
# Sample is 10,000 people for treatment group and control group 
sample=10000
# 
prop.test(x=c(sum(DisneyAB$TreatConv),sum(DisneyAB$ControlConv)), n=c(sample,sample), alternative = &quot;greater&quot;)</code></pre>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(sum(DisneyAB$TreatConv), sum(DisneyAB$ControlConv)) out of c(sample, sample)
## X-squared = 6.1471, df = 1, p-value = 0.006581
## alternative hypothesis: greater
## 95 percent confidence interval:
##  0.0007070449 1.0000000000
## sample estimates:
## prop 1 prop 2 
## 0.0047 0.0025</code></pre>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="instagram-ads-roi-return-on-investment-disney"
class="section level2">
<h2>6. Instagram Ads ROI (Return On Investment) (Disney)</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="figure-4" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/AloA.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. Calculate ROI to decide whether to continue on the Advertisement.]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="goal-5" class="section level3">
<h3>2. Goal</h3>
<p>To identify whether the conversion revenue is different between
converted treatment and control group. In addition, Return On Investment
(ROI) is calculated to decide whether to continue on the
advertisement.</p>
<p><br></p>
</div>
<div id="hypotheses-and-formula-of-roi" class="section level3">
<h3>3. Hypotheses and Formula of ROI:</h3>
<ul>
<li><p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>):</strong></p>
<p><span class="math display">\[
H_0: \mu_{\text{Treatment}} = \mu_{\text{Control}}
\]</span></p></li>
<li><p><strong>Alternative Hypothesis (<span
class="math inline">\(H_1\)</span>):</strong></p>
<p><span class="math display">\[
H_1: \mu_{\text{Treatment}} \neq \mu_{\text{Control}}
\]</span></p></li>
<li><p>The <strong>ROI</strong> is calculated as follows: Sample 10,000
people for treatment and control group. Total cost of experiment is
<span class="math inline">\(10,000 \times 0.2 = 20\)</span>.</p>
<p><span class="math display">\[
\text{ROI} = \frac{\text{Revenue}_{\text{Treatment}} -
\text{Revenue}_{\text{Control}} - \text{Cost}}{\text{Cost}}
\]</span></p></li>
</ul>
</div>
<div id="conclusion-1" class="section level3">
<h3>4. Conclusion:</h3>
<ul>
<li><p>At 0.05 significance level, the null hypothesis cannot be
rejected, indicating there is no statistically significant difference in
conversion revenue between the converted control and treatment group
exposed to Disney advertisement. Consequently, the experiment does not
provide sufficient evidence to conclude that the Disney advertisement
has a significant impact on the average conversion revenue among
converted users.</p></li>
<li><p>The Disney advertisement generates 305.95 times the return on
investment compared to the cost of running the advertisement, relative
to the control group.</p></li>
</ul>
<p><br></p>
</div>
<div id="code-5" class="section level3">
<h3>5. Code</h3>
<pre class="r"><code>### Subset the data
DisTRev &lt;- subset(DisneyAB$TreatRev, DisneyAB$TreatConv == 1)
DisCRev &lt;- subset(DisneyAB$ControlRev, DisneyAB$ControlConv == 1)

### Test Welch Two Sample t-test under the assumption that the variances between the two differ
t.test(DisTRev, DisCRev, alternative = &quot;two.sided&quot;, var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  DisTRev and DisCRev
## t = -0.34404, df = 40.45, p-value = 0.7326
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1068.5255   757.5723
## sample estimates:
## mean of x mean of y 
##  455.7234  611.2000</code></pre>
<pre class="r"><code>### ROI Disney 
(sum(DisTRev)-sum(DisCRev)-20)/20</code></pre>
<pre><code>## [1] 305.95</code></pre>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="instagram-ads-ab-testing-alo" class="section level2">
<h2>7. Instagram Ads A/B Testing (Alo)</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="figure-5" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/AloA.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. Decide whether to continue on the Ad based on Incremental
Conversion Rate]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="goal-6" class="section level3">
<h3>2. Goal</h3>
<p>To identify whether any treatment effect represented by Incremental
Conversion Rate (ICR) is positive.</p>
<p><br></p>
</div>
<div id="hypotheses-and-formula-of-icr-1" class="section level3">
<h3>3. Hypotheses and Formula of ICR</h3>
<ul>
<li><p>The <strong>Incremental Conversion Rate (ICR)</strong> is defined
as:</p>
<ul>
<li><p><strong>ICR</strong> (Incremental Conversion Rate):</p>
<p><span class="math display">\[
\text{ICR} = \text{Conversion\_Rate(Treatment)} -
\text{Conversion\_Rate(Control)}
\]</span></p></li>
<li><p><strong>Treatment group</strong>: Exposed to the
advertisement.<br />
</p></li>
<li><p><strong>Control group</strong>: Not exposed to the
advertisement.</p></li>
</ul></li>
<li><p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>):</strong></p>
<p><span class="math display">\[
H_0: \text{ICR} \leq 0 \quad \text{(The incremental conversion rate is
less than or equal to 0)}.
\]</span></p></li>
<li><p><strong>Alternative Hypothesis (<span
class="math inline">\(H_1\)</span>):</strong></p>
<p><span class="math display">\[
H_1: \text{ICR} &gt; 0 \quad \text{(The incremental conversion rate is
greater than 0)}.
\]</span></p></li>
</ul>
</div>
<div id="conclusion-2" class="section level3">
<h3>4. Conclusion:</h3>
<ul>
<li>The p-value obtained from this test allow us to reject the null
hypothesis. This indicates that the conversion rate in the treatment
group is statistically significantly greater than that in the control
group.</li>
</ul>
<p><br></p>
</div>
<div id="code-6" class="section level3">
<h3>5. Code</h3>
<pre class="r"><code>load(&quot;AloAB.Rdata&quot;) 
### tests for another data
### Proportion test for ICR
### ICR = Conversion_Rate(Treatment) − Conversion_Rate(Control)
# Assign 10,000 units for both treatment and control groups 
sample=10000
prop.test(x=c(sum(AloAB$TreatConv),sum(AloAB$ControlConv)), n=c(sample,sample), alternative = &quot;greater&quot;)</code></pre>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(sum(AloAB$TreatConv), sum(AloAB$ControlConv)) out of c(sample, sample)
## X-squared = 17.926, df = 1, p-value = 1.149e-05
## alternative hypothesis: greater
## 95 percent confidence interval:
##  0.002874909 1.000000000
## sample estimates:
## prop 1 prop 2 
## 0.0086 0.0038</code></pre>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="instagram-ads-roi-return-on-investment-alo"
class="section level2">
<h2>8. Instagram Ads ROI (Return On Investment) (Alo)</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="figure-6" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/AloA.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. Calculate ROI to decide whether to continue on the Advertisement]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="goal-7" class="section level3">
<h3>2. Goal</h3>
<p>To identify whether the conversion revenue is different between
converted treatment and control group. In addition, Return On Investment
(ROI) is calculated to decide whether to continue on the
advertisement.</p>
<p><br></p>
</div>
<div id="hypotheses-and-formula-of-roi-1" class="section level3">
<h3>3. Hypotheses and Formula of ROI:</h3>
<ul>
<li><p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>):</strong></p>
<p><span class="math display">\[
H_0: \mu_{\text{Treatment}} = \mu_{\text{Control}}
\]</span></p></li>
<li><p><strong>Alternative Hypothesis (<span
class="math inline">\(H_1\)</span>):</strong></p>
<p><span class="math display">\[
H_1: \mu_{\text{Treatment}} \neq \mu_{\text{Control}}
\]</span></p></li>
<li><p>The <strong>ROI</strong> is calculated as follows:<br />
Sample 10,000 people for the treatment and control groups.<br />
Total cost of the experiment is <span class="math inline">\(10,000
\times 0.2 = \$20\)</span>.</p>
<p><span class="math display">\[
\text{ROI} = \frac{\text{Revenue}_{\text{Treatment}} -
\text{Revenue}_{\text{Control}} - \text{Cost}}{\text{Cost}}
\]</span></p></li>
</ul>
</div>
<div id="conclusion-3" class="section level3">
<h3>4. Conclusion:</h3>
<ul>
<li><p>At 0.05 significance level, the null hypothesis cannot be
rejected, indicating there is no statistically significant difference in
conversion revenue between the converted control and treatment group
exposed to Alo advertisement. Consequently, the experiment does not
provide sufficient evidence to conclude that the Alo advertisement has a
significant impact on the average conversion revenue among converted
users.</p></li>
<li><p>In case of ROI of the Alo advertisement, the treatment group
exposed to the advertisement 0.3655 times the return on investment
compared to the cost of running the advertisement, relative to the
control group. This indicates that the Alo advertisement is less
effective to generate more revenue from the treatment group compared to
the control group.</p></li>
</ul>
<p><br></p>
</div>
<div id="code-7" class="section level3">
<h3>5. Code</h3>
<pre class="r"><code>AloTRev &lt;- subset(AloAB$TreatRev, AloAB$TreatConv == 1)
AloCRev &lt;- subset(AloAB$ControlRev, AloAB$ControlConv == 1)
t.test(AloTRev, AloCRev, alternative = &quot;two.sided&quot;, var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  AloTRev and AloCRev
## t = -0.35691, df = 58.769, p-value = 0.7224
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.3206978  0.9209059
## sample estimates:
## mean of x mean of y 
## 0.7272093 0.9271053</code></pre>
<pre class="r"><code>(sum(AloTRev)-sum(AloCRev)-20)/20</code></pre>
<pre><code>## [1] 0.3655</code></pre>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="hypothesis-testing-with-multiple-treatments"
class="section level2">
<h2>9. Hypothesis Testing with Multiple Treatments</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="figure-7" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/Nutrition.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. Do Nutrition Labels Encourage Healthier Eating?]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="objective" class="section level3">
<h3>2. Objective</h3>
<p>To determine if there is any difference in the average nutrition
score of shopping baskets across different labeling treatments for an
online grocer. The treatments include: - <strong>Star Nutrition
Labels</strong> - <strong>Letter Grade Nutrition Labels</strong> -
<strong>Warning Labels</strong> - <strong>Control Group (No
Labels)</strong></p>
<p>Dependent variable: Average nutrition score of the shopping
basket.</p>
<p><br></p>
</div>
<div id="methodology-2" class="section level3">
<h3>3. Methodology</h3>
<div id="a-visualization" class="section level4">
<h4>(a) Visualization</h4>
<p>Using boxplots to compare the basket scores across treatments.</p>
<pre class="r"><code>getwd()</code></pre>
<pre><code>## [1] &quot;C:/Github/jennyjihyunseo.github.io&quot;</code></pre>
<pre class="r"><code>file_path &lt;- &quot;C:/Users/sjh50/OneDrive/문서/UC Davis/Paul/Github/Lecture2/Grocery.Rdata&quot;
load(&quot;Grocery.Rdata&quot;)

library(DescTools)
library(ggplot2)</code></pre>
<pre class="r"><code>summary(Grocery$BasketScore[Grocery$Condition==&quot;Control&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.90   47.55   54.56   55.27   63.14  100.00</code></pre>
<pre class="r"><code>summary(Grocery$BasketScore[Grocery$Condition==&quot;Star&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   22.04   48.52   57.74   57.45   66.27   94.67</code></pre>
<pre class="r"><code>summary(Grocery$BasketScore[Grocery$Condition==&quot;Letter&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   19.46   50.02   57.86   58.46   67.36  100.00</code></pre>
<pre class="r"><code>summary(Grocery$BasketScore[Grocery$Condition==&quot;Warn&quot;])</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   25.33   52.95   60.77   60.65   69.81   98.85</code></pre>
<pre class="r"><code>### ggplot 
ggplot(Grocery, aes(x=Condition, y=BasketScore, fill=Condition)) + 
geom_boxplot()+
 theme(text = element_text(size = 20))</code></pre>
<p><img src="stat2_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="b-anova-test" class="section level4">
<h4>(b) ANOVA Test</h4>
<p>To test for significant differences in means among treatments.</p>
<pre class="r"><code>### ANOVA test to identify whether there is significant difference in the mean among different treatments 
anova &lt;-aov(BasketScore ~ Condition, data = Grocery)
summary(anova)</code></pre>
<pre><code>##               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Condition      3   7479  2493.0   16.09 2.45e-10 ***
## Residuals   1996 309221   154.9                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>)</strong>: <span
class="math display">\[
H_0: \mu_{\text{Star}} = \mu_{\text{Letter}} = \mu_{\text{Warning}} =
\mu_{\text{Control}}
\]</span></p>
<p><strong>Alternative Hypothesis (<span
class="math inline">\(H_A\)</span>)</strong>: <span
class="math display">\[
H_A: \text{At least one group mean is different.}
\]</span></p>
<p>At 0.05 significance level, the null hypothesis can be rejected. It
concludes that at least one treatment mean is different. In order to
find which treatment differs, TukeyHSD is used for finding.</p>
</div>
<div id="c-tukeyhsd-test" class="section level4">
<h4>(c) TukeyHSD Test</h4>
<p>To identify which treatments differ.</p>
<pre class="r"><code>TukeyHSD(anova)</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = BasketScore ~ Condition, data = Grocery)
## 
## $Condition
##                     diff        lwr      upr     p adj
## Letter-Control  3.189506  1.1654647 5.213548 0.0003077
## Star-Control    2.178433  0.1543914 4.202475 0.0291183
## Warn-Control    5.375293  3.3512514 7.399335 0.0000000
## Star-Letter    -1.011073 -3.0351150 1.012968 0.5729945
## Warn-Letter     2.185787  0.1617451 4.209828 0.0283479
## Warn-Star       3.196860  1.1728183 5.220902 0.0002959</code></pre>
<p>Interpretation: (1) Letter - Control: There is a statistically
significant difference in basket score between Letter Nutrition Labels
and no labels. If there are letter nutrition labels, it encourages
customers to buy healthier groceries while increasing the basket scores
by 3.18 units compared to the control group. (2) Star - Control: There
is a statistically significant difference in basket score between Star
Nutrition Labels and no labels (control). When Star Nutrition Labels are
displayed, they encourage customers to buy healthier groceries,
increasing the basket score by 2.18 units compared to the control group.
(3) Warn - Control: There is a statistically significant difference in
basket score between Warn Nutrition Labels and no labels. Warning Labels
have the strongest effect, leading to a increase of 5.38 units in basket
scores compared to the control group. (4) Warn - Letter: When comparing
Warning Nutrition Labels and Letter Nutrition Labels, there is a
statistically significant difference in basket scores. Warning Labels
are more effective, increasing basket scores by 2.18 units compared to
Letter Nutrition Labels. (5) Warn - Star: When comparing Warning
Nutrition Labels and Star Nutrition Labels, there is a statistically
significant difference in basket scores. Warning Labels are more
effective, increasing basket scores by 3.19 units compared to Star
Nutrition Labels. (6) Star - Letter: It is not statistically significant
in basket scores between Star and Letter labels.</p>
</div>
<div id="d-regression-analysis" class="section level4">
<h4>(d) Regression Analysis</h4>
<pre class="r"><code>### Regression
OLS &lt;- lm(Grocery$BasketScore ~ Grocery$Condition)
summary(OLS)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Grocery$BasketScore ~ Grocery$Condition)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.998  -8.141  -0.286   8.677  44.730 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              55.2703     0.5566  99.294  &lt; 2e-16 ***
## Grocery$ConditionLetter   3.1895     0.7872   4.052 5.28e-05 ***
## Grocery$ConditionStar     2.1784     0.7872   2.767   0.0057 ** 
## Grocery$ConditionWarn     5.3753     0.7872   6.828 1.14e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.45 on 1996 degrees of freedom
## Multiple R-squared:  0.02362,    Adjusted R-squared:  0.02215 
## F-statistic: 16.09 on 3 and 1996 DF,  p-value: 2.45e-10</code></pre>
<p>At a 0.05 significance level, the overall model is statistically
significant but R-squared is low. Only 2.3% of the variation in the
dependent variable is explained by independent variables. In terms of
coefficients of the independent variables, all coefficients are
statistically significant at 0.05 significance level. The baseline
Basket Score for the control group is 55.27 units, meaning that the
average basket scores without labels is 55.27 units. In case of Warning
Nutrition Labels, if there is one unit increase in the use of Warning
Nutrition Labels, basket scores increase by 5.37 units on average.</p>
<p><br></p>
</div>
</div>
<div id="additional-analyses" class="section level3">
<h3>4. Additional Analyses</h3>
<div id="a-dunnetts-test" class="section level4">
<h4>(a) Dunnett’s Test</h4>
<p>Dunnett’s Test is specifically designed to compare the control group
with each of the treatment groups individually.</p>
<pre class="r"><code>DunnettTest(x=Grocery$BasketScore, g=Grocery$Condition)</code></pre>
<pre><code>## 
##   Dunnett&#39;s test for comparing several treatments with a control :  
##     95% family-wise confidence level
## 
## $Control
##                    diff    lwr.ci   upr.ci    pval    
## Letter-Control 3.189506 1.3388959 5.040117 0.00016 ***
## Star-Control   2.178433 0.3278227 4.029044 0.01582 *  
## Warn-Control   5.375293 3.5246827 7.225904 2.4e-11 ***
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Interpretation: All treatment groups increase the basket scores
compared to the control group which means that all of them are effective
to encourage people to buy healthier food. In case of Warning Nutrition
Labels, it is the most effective labeling method compared to the other
options by increasing 5.37 units of the basket scores.</p>
</div>
<div id="b-binary-analysis-warning-vs.-others" class="section level4">
<h4>(b) Binary Analysis: Warning vs. Others</h4>
<pre class="r"><code># Make Warning Nutrition Labels as 1 and the other labels (Control, Letter, Star) as 0
Grocery$Warning &lt;- 0
Grocery$Warning[Grocery$Condition == &quot;Warn&quot;] &lt;- 1</code></pre>
<pre class="r"><code>OLS2 &lt;- lm(Grocery$BasketScore ~ Grocery$Warning)
summary(OLS2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Grocery$BasketScore ~ Grocery$Warning)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.156  -8.304  -0.095   8.857  42.940 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      57.0596     0.3226 176.880  &lt; 2e-16 ***
## Grocery$Warning   3.5860     0.6452   5.558 3.09e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.49 on 1998 degrees of freedom
## Multiple R-squared:  0.01523,    Adjusted R-squared:  0.01473 
## F-statistic: 30.89 on 1 and 1998 DF,  p-value: 3.092e-08</code></pre>
<p>When there are not Warning Nutrition Labels, the average basket score
is 57.06. If there is Warning Nutrition Labels, it increases the basket
scores by 3.58 units. At 0.05 significance level, the coefficient of
Warning Labels is statistically significant. The overall model is valid
due to the p-value less than 0.05 significance level.</p>
<p>Compare the mean difference between Warning Nutrition Labels and the
other label options to identify any significant mean difference in
Waring Nutrition Labels in the basket scores compared with the other
options.</p>
<p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>)</strong>: <span
class="math display">\[
H_0: \mu_{\text{Warning}} \leq \mu_{\text{Other}}
\]</span></p>
<p><strong>Alternative Hypothesis (<span
class="math inline">\(H_A\)</span>)</strong>: <span
class="math display">\[
H_A: \mu_{\text{Warning}} &gt; \mu_{\text{Other}}
\]</span></p>
<pre class="r"><code>t.test(Grocery$BasketScore[Grocery$Warning==1], Grocery$BasketScore[Grocery$Warning==0], alternative = &quot;greater&quot;, var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Grocery$BasketScore[Grocery$Warning == 1] and Grocery$BasketScore[Grocery$Warning == 0]
## t = 5.4558, df = 829.19, p-value = 3.22e-08
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  2.503641      Inf
## sample estimates:
## mean of x mean of y 
##  60.64558  57.05960</code></pre>
<p>At 0.05 significance level, the null hypothesis can be rejected.
There is a statistically significant mean difference in the basket
scores between Warning Nutrition Labels and other Label options and the
mean basket scores of Warning Nutrition Labels is greater than the other
labels.</p>
</div>
</div>
<div id="pairwise-comparisons" class="section level3">
<h3>5. Pairwise Comparisons</h3>
<div id="a-warning-vs.-nutrition-star-letter" class="section level4">
<h4>(a) Warning vs. Nutrition (Star + Letter)</h4>
<pre class="r"><code># Combine Letter and Star as Nutrition
Grocery$Condition2 &lt;- Grocery$Condition
Grocery$Condition2[Grocery$Condition == &quot;Letter&quot; | Grocery$Condition == &quot;Star&quot;] &lt;- &quot;Nutrition&quot;

t.test(Grocery$BasketScore[Grocery$Condition2 == &quot;Warn&quot;], 
       Grocery$BasketScore[Grocery$Condition2 == &quot;Nutrition&quot;], 
       alternative = &quot;greater&quot;, 
       var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Grocery$BasketScore[Grocery$Condition2 == &quot;Warn&quot;] and Grocery$BasketScore[Grocery$Condition2 == &quot;Nutrition&quot;]
## t = 3.8696, df = 967.64, p-value = 5.815e-05
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  1.546231      Inf
## sample estimates:
## mean of x mean of y 
##  60.64558  57.95425</code></pre>
<p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>)</strong>: <span
class="math display">\[
H_0: \mu_{\text{Warn}} \leq \mu_{\text{Nutrition}}
\]</span></p>
<p><strong>Alternative Hypothesis (<span
class="math inline">\(H_A\)</span>)</strong>: <span
class="math display">\[
H_A: \mu_{\text{Warn}} &gt; \mu_{\text{Nutrition}}
\]</span> At 0.05 significance level, the null hypothesis can be
rejected. The mean basket scores of Warning Nutrition Labels are greater
than the mean basket scores of combined Nutrition (Star and Letter)
Labels.</p>
</div>
<div id="b-nutrition-star-letter-vs.-control" class="section level4">
<h4>(b) Nutrition (Star + Letter) vs. Control</h4>
<pre class="r"><code>t.test(Grocery$BasketScore[Grocery$Condition2==&quot;Nutrition&quot;], 
       Grocery$BasketScore[Grocery$Condition2==&quot;Control&quot;], 
       alternative = &quot;greater&quot;, 
       var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Grocery$BasketScore[Grocery$Condition2 == &quot;Nutrition&quot;] and Grocery$BasketScore[Grocery$Condition2 == &quot;Control&quot;]
## t = 4.0079, df = 1017.4, p-value = 3.286e-05
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  1.581467      Inf
## sample estimates:
## mean of x mean of y 
##  57.95425  55.27028</code></pre>
<p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>)</strong>: <span
class="math display">\[
H_0: \mu_{\text{Nutrition}} \leq \mu_{\text{Control}}
\]</span></p>
<p><strong>Alternative Hypothesis (<span
class="math inline">\(H_A\)</span>)</strong>: <span
class="math display">\[
H_A: \mu_{\text{Nutrition}} &gt; \mu_{\text{Control}}
\]</span> At 0.05 significance level, there is a statistically
significant difference in the basket scores between Nutrition labels
(Star and Letter) and Control groups. The null hypothesis can be
rejected and the mean basket scores of Nutrition labels (Star and
Letter) is greater than the mean basket scores of control groups.</p>
<p><br></p>
</div>
</div>
<div id="conclusion-4" class="section level3">
<h3>6. Conclusion</h3>
<ul>
<li>Warning Labels are the most effective treatment, significantly
increasing basket scores compared to all other treatments and the
Control group.</li>
<li>Nutrition Labels (Star + Letter) are also effective but less
impactful than Warning Labels.</li>
<li>Future recommendations could focus on optimizing the design and
implementation of Warning Labels to maximize their impact on healthier
grocery choices.</li>
</ul>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="parametric-and-non-parametric-regression-analysis"
class="section level2">
<h2>10. Parametric and Non-parametric Regression Analysis</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<p><br><br><br></p>
<div id="figure-8" class="section level3">
<h3>1. Figure</h3>
<p align="center">
<img src="images/Regression.png" style="width:80%; height:auto;" align="center">
</p>
<p align="center">
[Fig. To Determine whether a Parametric or Non-parametric fit well with
the data.]
</p>
<p><br></p>
<p><br><br></p>
</div>
<div id="objective-1" class="section level3">
<h3>2. Objective</h3>
<p>To analyze the relationship between <strong>Price</strong> and
<strong>Unit Sales</strong> using various regression approaches,
including linear, non-linear, and non-parametric models.</p>
<p><br></p>
</div>
<div id="methodology-3" class="section level3">
<h3>2. Methodology</h3>
<div id="a-data-preparation" class="section level4">
<h4>(a) Data Preparation</h4>
<pre class="r"><code>load(&quot;Prices.Rdata&quot;)</code></pre>
</div>
<div id="b-visualizations" class="section level4">
<h4>(b) Visualizations</h4>
<div id="i-boxplot-of-unit-sales-by-price-categorical"
class="section level5">
<h5>(i) Boxplot of Unit Sales by Price (Categorical)</h5>
<pre class="r"><code>### Make a factor variable of prices to convert a continous variable into a categorical variable 
prices$PriceFactor &lt;- as.factor(prices$Price)
### Figures using price as a factor
ggplot(prices, aes(x=PriceFactor, y=UnitSales)) + 
 geom_boxplot()</code></pre>
<p><img src="stat2_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
<div id="ii-scatterplot-of-unit-sales-vs.-price-continuous"
class="section level5">
<h5>(ii) Scatterplot of Unit Sales vs. Price (Continuous)</h5>
<p>Linear Trend:</p>
<pre class="r"><code>ggplot(prices, aes(x=Price, y=UnitSales)) + 
 geom_point() +
 geom_smooth(method=lm)</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="stat2_files/figure-html/unnamed-chunk-27-1.png" width="672" />
Non-linear Trend (Loess):</p>
<pre class="r"><code>ggplot(prices, aes(x=Price, y=UnitSales)) + 
 geom_point() +
 geom_smooth(method = &quot;loess&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="stat2_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p><br></p>
</div>
</div>
<div id="c-regression-models" class="section level4">
<h4>(c) Regression Models</h4>
<div id="i-linear-regression-price-as-continuous"
class="section level5">
<h5>(i) Linear Regression (Price as Continuous)</h5>
<pre class="r"><code>### Simple Regression Models
 OLS1 &lt;- lm(prices$UnitSales ~ prices$Price)
 summary(OLS1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = prices$UnitSales ~ prices$Price)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -237.037  -53.092    2.408   52.501  219.927 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1521.353     14.223  106.96   &lt;2e-16 ***
## prices$Price -557.408      9.333  -59.72   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 75.5 on 998 degrees of freedom
## Multiple R-squared:  0.7814, Adjusted R-squared:  0.7811 
## F-statistic:  3567 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interpretation: The above linear relationship while treating Price as
a continuous variable. The Price coefficient is statistically
significant at 0.05 significance level. When the Price increases by 1
unit, the Unit sales decreases by 557.408 units.</p>
</div>
<div id="ii-linear-regression-price-as-categorical"
class="section level5">
<h5>(ii) Linear Regression (Price as Categorical)</h5>
<pre class="r"><code>OLS2 &lt;- lm(prices$UnitSales ~ prices$PriceFactor)
summary(OLS2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = prices$UnitSales ~ prices$PriceFactor)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -224.580  -47.970    0.937   51.335  200.208 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             878.752      6.930 126.811  &lt; 2e-16 ***
## prices$PriceFactor1.19  -33.173     10.368  -3.199  0.00142 ** 
## prices$PriceFactor1.29  -65.624      9.800  -6.696 3.57e-11 ***
## prices$PriceFactor1.39 -112.129      9.692 -11.569  &lt; 2e-16 ***
## prices$PriceFactor1.49 -166.827      9.573 -17.427  &lt; 2e-16 ***
## prices$PriceFactor1.59 -223.073      9.800 -22.763  &lt; 2e-16 ***
## prices$PriceFactor1.69 -281.248      9.446 -29.773  &lt; 2e-16 ***
## prices$PriceFactor1.79 -372.416      9.917 -37.553  &lt; 2e-16 ***
## prices$PriceFactor1.89 -442.961      9.573 -46.273  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 72.35 on 991 degrees of freedom
## Multiple R-squared:  0.8007, Adjusted R-squared:  0.7991 
## F-statistic: 497.6 on 8 and 991 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Interpretation: Compared to the linear regression model with the same
coefficient slope making the linearly decreasing regression model, when
making Price variable as a categorical variable, the coefficient
variables vary depending on different price factors, indicating the
relationship between Unit sales and Price factors is non-linear.</p>
</div>
<div id="iii-polynomial-regression" class="section level5">
<h5>(iii) Polynomial Regression</h5>
<pre class="r"><code># Add higher-order terms for polynomial regression
prices$PriceSq &lt;- prices$Price^2
prices$PriceCu &lt;- prices$Price^3

OLS3 &lt;- lm(prices$UnitSales ~ prices$Price + prices$PriceSq + prices$PriceCu)
summary(OLS3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = prices$UnitSales ~ prices$Price + prices$PriceSq + 
##     prices$PriceCu)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -226.879  -49.056   -0.159   51.812  202.625 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)      819.46     571.58   1.434    0.152
## prices$Price     339.71    1185.53   0.287    0.775
## prices$PriceSq  -227.29     806.27  -0.282    0.778
## prices$PriceCu   -32.03     179.96  -0.178    0.859
## 
## Residual standard error: 72.3 on 996 degrees of freedom
## Multiple R-squared:  0.7999, Adjusted R-squared:  0.7993 
## F-statistic:  1327 on 3 and 996 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="iv-log-linear-regression" class="section level5">
<h5>(iv) Log-Linear Regression</h5>
<pre class="r"><code>prices$LnPrice &lt;- log(prices$Price)
OLS4 &lt;- lm(prices$UnitSales ~ prices$LnPrice)
summary(OLS4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = prices$UnitSales ~ prices$LnPrice)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -237.877  -56.347    1.859   54.759  228.611 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     998.438      6.166  161.92   &lt;2e-16 ***
## prices$LnPrice -802.288     14.364  -55.85   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 79.5 on 998 degrees of freedom
## Multiple R-squared:  0.7576, Adjusted R-squared:  0.7574 
## F-statistic:  3119 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="v-exponential-regression" class="section level5">
<h5>(v) Exponential Regression</h5>
<pre class="r"><code>prices$ExpPrice &lt;- exp(prices$Price)
OLS5 &lt;- lm(prices$UnitSales ~ prices$ExpPrice)
summary(OLS5)</code></pre>
<pre><code>## 
## Call:
## lm(formula = prices$UnitSales ~ prices$ExpPrice)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -229.673  -50.011    0.303   50.166  203.604 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     1255.852      9.372  134.00   &lt;2e-16 ***
## prices$ExpPrice -123.264      1.959  -62.93   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 72.45 on 998 degrees of freedom
## Multiple R-squared:  0.7987, Adjusted R-squared:  0.7985 
## F-statistic:  3960 on 1 and 998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
<div id="results-comparison" class="section level3">
<h3>3. Results Comparison</h3>
<ul>
<li><strong>Polynomial Regression (OLS3)</strong>: Captures non-linear
patterns with significant coefficients for higher-order terms.</li>
<li><strong>Log-Linear Regression (OLS4)</strong>: Provides a
logarithmic fit, indicating percentage changes in Unit Sales relative to
Price changes.</li>
<li><strong>Exponential Regression (OLS5)</strong>: Models rapid
increases or decreases in Unit Sales.</li>
<li><strong>Non-Parametric (Price as Categorical)</strong>: Achieves the
highest Adjusted R-squared value (0.7791) and the lowest residual
standard error. However, non-parametric models have limited scalability
outside experimental price points.</li>
</ul>
</div>
<div id="conclusion-5" class="section level3">
<h3>4. Conclusion</h3>
<p>Among the models, treating Price as a categorical variable yielded
the best fit (highest Adjusted R-squared). However, for prediction
purposes, polynomial and log-linear regressions are more scalable and
practical for prices beyond the experimental range.</p>
<p><br></p>
<p><br><br><br></p>
</div>
</div>
<div id="savings-analysis" class="section level2">
<h2>11. Savings Analysis</h2>
<p><img src="https://img.shields.io/badge/Using-R-blue" /></p>
<p><br></p>
<div id="objective-2" class="section level3">
<h3>1. Objective</h3>
<p>To analyze the impact of treatment on deposit amounts across
different income groups and age categories using t-tests and regression
models. The analysis also explores conditional average treatment effects
(CATEs) to identify individual-level treatment heterogeneity.</p>
<p><br></p>
</div>
<div id="methodology-4" class="section level3">
<h3>2. Methodology</h3>
<div id="a-visualizations" class="section level4">
<h4>(a) Visualizations</h4>
<div id="i-deposits-by-age-and-treatment-group" class="section level5">
<h5>(i) Deposits by Age and Treatment Group</h5>
<pre class="r"><code>load(&quot;Savings.Rdata&quot;)</code></pre>
<pre class="r"><code>ggplot(Savings, aes(x=Age, y=Deposits, color=TreatGroup)) + 
  geom_point() +
  geom_smooth(method=lm, aes(group=TreatGroup))</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="stat2_files/figure-html/unnamed-chunk-35-1.png" width="672" />
##### (ii) Deposits by Income and Treatment Group</p>
<pre class="r"><code>ggplot(Savings, aes(x=Income, y=Deposits, color=TreatGroup)) + 
  geom_point() +
  geom_smooth(method=lm, aes(group=TreatGroup))</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="stat2_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
</div>
</div>
<div id="b-group-comparisons-using-t-tests" class="section level4">
<h4>(b) Group Comparisons Using t-tests</h4>
<div id="i-create-income-groups-and-age-dummies" class="section level5">
<h5>(i) Create Income Groups and Age Dummies</h5>
<p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>)</strong>:</p>
<p><span class="math display">\[
H_0: \mu_{\text{Treatment}} \leq \mu_{\text{Control}}
\]</span></p>
<p><strong>Alternative Hypothesis (<span
class="math inline">\(H_A\)</span>)</strong>:</p>
<p><span class="math display">\[
H_A: \mu_{\text{Treatment}} &gt; \mu_{\text{Control}}
\]</span></p>
<pre class="r"><code>### t-tests by group
### Income group and age dummies
Savings$Age35 &lt;- ifelse(Savings$Age&gt;=35, 1, 0)
Savings$IncGrp &lt;- &quot;&lt;$50K&quot;
Savings$IncGrp &lt;- ifelse(Savings$Income&gt;=50000, &quot;$50-100K&quot;, Savings$IncGrp)
Savings$IncGrp &lt;- ifelse(Savings$Income&gt;100000, &quot;&gt;$100K&quot;, Savings$IncGrp)

### t-tests
INC1t &lt;- subset(Savings$Deposits, Savings$TreatGroup == 1 &amp;     Savings$IncGrp==&quot;&lt;$50K&quot;)

INC1c &lt;- subset(Savings$Deposits, Savings$TreatGroup == 0 &amp;  Savings$IncGrp==&quot;&lt;$50K&quot;)

INC2t &lt;- subset(Savings$Deposits, Savings$TreatGroup == 1 &amp; Savings$IncGrp==&quot;$50-100K&quot;)

INC2c &lt;- subset(Savings$Deposits, Savings$TreatGroup == 0 &amp; Savings$IncGrp==&quot;$50-100K&quot;)

INC3t &lt;- subset(Savings$Deposits, Savings$TreatGroup == 1 &amp; Savings$IncGrp==&quot;&gt;$100K&quot;)

INC3c &lt;- subset(Savings$Deposits, Savings$TreatGroup == 0 &amp; Savings$IncGrp==&quot;&gt;$100K&quot;)

INCt &lt;- subset(Savings$Deposits, Savings$TreatGroup == 1)
INCc &lt;- subset(Savings$Deposits, Savings$TreatGroup == 0)

### Entire population
t.test(INCt, INCc, alternative = &quot;greater&quot;, var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  INCt and INCc
## t = 14.724, df = 4950.6, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  476.9293      Inf
## sample estimates:
## mean of x mean of y 
##  1918.569  1381.646</code></pre>
<p>Compare the deposit amounts between control group and treatment group
to identify if there is any difference in mean deposit amounts between
the two groups. At 0.05 significance level, the null hypothesis can be
rejected and the mean deposit amount of the treatment group is greater
than the mean deposit amount of the control group.</p>
</div>
<div id="ii-perform-t-tests-for-each-income-group"
class="section level5">
<h5>(ii) Perform t-tests for Each Income Group</h5>
<p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>)</strong>: <span
class="math display">\[
H_0: \mu_{\text{Treatment, Income Group 1}} \leq \mu_{\text{Control,
Income Group 1}}
\]</span></p>
<p><strong>Alternative Hypothesis (<span
class="math inline">\(H_A\)</span>)</strong>: <span
class="math display">\[
H_A: \mu_{\text{Treatment, Income Group 1}} &gt; \mu_{\text{Control,
Income Group 1}}
\]</span></p>
<pre class="r"><code>### Income group 1 (&lt;$50K)
t.test(INC1t, INC1c, alternative = &quot;greater&quot;, var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  INC1t and INC1c
## t = 11.469, df = 2831.4, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  468.0417      Inf
## sample estimates:
## mean of x mean of y 
##  1794.196  1247.762</code></pre>
<p>In the income group 1 (&lt;$50K), the null hypothesis can be rejected
at 0.05 significance level, the mean deposit amount of the treatment
group in the income group 1 is greater than the mean deposit amount of
the control group in the income group 1.</p>
<p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>)</strong>: <span
class="math display">\[
H_0: \mu_{\text{Treatment, Income Group 2}} \leq \mu_{\text{Control,
Income Group 2}}
\]</span></p>
<p><strong>Alternative Hypothesis (<span
class="math inline">\(H_A\)</span>)</strong>: <span
class="math display">\[
H_A: \mu_{\text{Treatment, Income Group 2}} &gt; \mu_{\text{Control,
Income Group 2}}
\]</span></p>
<pre class="r"><code>### Income group 2 ($50-100K)
t.test(INC2t, INC2c, alternative = &quot;greater&quot;, var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  INC2t and INC2c
## t = 9.6702, df = 1750.4, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  487.889     Inf
## sample estimates:
## mean of x mean of y 
##  2057.428  1469.479</code></pre>
<p>In the income group 2 ($50K-$100K), the null hypothesis can be
rejected at 0.05 significance level, the mean deposit amount of the
treatment group in the income group 2 is greater than the mean deposit
amount of the control group in the income group 2.</p>
<p><strong>Null Hypothesis (<span
class="math inline">\(H_0\)</span>)</strong>: <span
class="math display">\[
H_0: \mu_{\text{Treatment, Income Group 3}} \leq \mu_{\text{Control,
Income Group 3}}
\]</span> <strong>Alternative Hypothesis (<span
class="math inline">\(H_A\)</span>)</strong>:</p>
<p><span class="math display">\[
H_A: \mu_{\text{Treatment, Income Group 3}} &gt; \mu_{\text{Control,
Income Group 3}}
\]</span></p>
<pre class="r"><code>### Income group 3 (&gt;$100K)
t.test(INC3t, INC3c, alternative = &quot;greater&quot;, var.equal = FALSE)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  INC3t and INC3c
## t = 1.1251, df = 354.7, p-value = 0.1307
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  -70.0936      Inf
## sample estimates:
## mean of x mean of y 
##  2215.043  2064.558</code></pre>
<p>In the income group 3 (&gt;$100K), the null hypothesis can be
rejected at 0.05 significance level, the mean deposit amount of the
treatment group in the income group 3 is greater than the mean deposit
amount of the control group in the income group 3.</p>
<p><br></p>
</div>
</div>
</div>
<div id="regression-analysis" class="section level3">
<h3>3. Regression Analysis</h3>
<div id="a-model-1-income-group-treatment-effects"
class="section level4">
<h4>(a) Model 1: Income Group Treatment Effects</h4>
<pre class="r"><code>### A regression approach
### Create Variables
Savings$INC1&lt;- ifelse(Savings$IncGrp==&quot;&lt;$50K&quot;,1,0)
Savings$INC2 &lt;- ifelse(Savings$IncGrp==&quot;$50-100K&quot;,1,0)
Savings$INC3 &lt;- ifelse(Savings$IncGrp==&quot;&gt;$100K&quot;,1,0)
Savings$TreatInc1 &lt;- Savings$TreatGroup * Savings$INC1
Savings$TreatInc2 &lt;- Savings$TreatGroup * Savings$INC2
Savings$TreatInc3 &lt;- Savings$TreatGroup * Savings$INC3
### First Model
OLS&lt;-lm(Savings$Deposits ~ Savings$TreatInc1 + Savings$TreatInc2 + Savings$TreatInc3 + Savings$INC1 + Savings$INC2 + Savings$INC3)
summary(OLS)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Savings$Deposits ~ Savings$TreatInc1 + Savings$TreatInc2 + 
##     Savings$TreatInc3 + Savings$INC1 + Savings$INC2 + Savings$INC3)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2929.2  -945.9     8.7   900.2  3336.3 
## 
## Coefficients: (1 not defined because of singularities)
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        2064.56      97.77  21.116  &lt; 2e-16 ***
## Savings$TreatInc1   546.43      47.62  11.476  &lt; 2e-16 ***
## Savings$TreatInc2   587.95      60.58   9.705  &lt; 2e-16 ***
## Savings$TreatInc3   150.48     135.09   1.114    0.265    
## Savings$INC1       -816.80     103.26  -7.910 3.15e-15 ***
## Savings$INC2       -595.08     106.40  -5.593 2.35e-08 ***
## Savings$INC3            NA         NA      NA       NA    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1275 on 4994 degrees of freedom
## Multiple R-squared:  0.06102,    Adjusted R-squared:  0.06008 
## F-statistic: 64.91 on 5 and 4994 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretation</strong>: - The intercept represents deposits
for the control group in Income Group 3 (&gt;$100K): 2064.56 units. -
<strong>Treatment Effects</strong>: - Income Group 1: +546.43 units
(statistically significant). - Income Group 2: +587.95 units
(statistically significant). - Income Group 3: +150.84 units (not
statistically significant). - Income groups except for Income group 3
has the lower savings amount compared to the Income group 3. - The
treatment is the difference in the savings amount between the control
group and the treatment group for each income group.</p>
</div>
<div id="b-model-2-interaction-of-treatment-and-income-groups"
class="section level4">
<h4>(b) Model 2: Interaction of Treatment and Income Groups</h4>
<pre class="r"><code>OLS &lt;- lm(Savings$Deposits ~ Savings$TreatGroup * Savings$IncGrp)
summary(OLS)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Savings$Deposits ~ Savings$TreatGroup * Savings$IncGrp)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2929.2  -945.9     8.7   900.2  3336.3 
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                              1469.48      41.98  35.002  &lt; 2e-16
## Savings$TreatGroup                        587.95      60.58   9.705  &lt; 2e-16
## Savings$IncGrp&lt;$50K                      -221.72      53.54  -4.141 3.51e-05
## Savings$IncGrp&gt;$100K                      595.08     106.40   5.593 2.35e-08
## Savings$TreatGroup:Savings$IncGrp&lt;$50K    -41.52      77.05  -0.539  0.59004
## Savings$TreatGroup:Savings$IncGrp&gt;$100K  -437.46     148.05  -2.955  0.00314
##                                            
## (Intercept)                             ***
## Savings$TreatGroup                      ***
## Savings$IncGrp&lt;$50K                     ***
## Savings$IncGrp&gt;$100K                    ***
## Savings$TreatGroup:Savings$IncGrp&lt;$50K     
## Savings$TreatGroup:Savings$IncGrp&gt;$100K ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1275 on 4994 degrees of freedom
## Multiple R-squared:  0.06102,    Adjusted R-squared:  0.06008 
## F-statistic: 64.91 on 5 and 4994 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretation</strong>: In the first regression model, it
represents the treatment effect for each income group. The first
regression shows different income levels affect the amount of deposits
without any treatment effect. However, the most important thing to
discuss is that it represents the treatment effect for each income
group. Therefore, this regression model shows the treatment effect for
each income level comparing with the control group for each income
group. In contrast, the second regression model shows the baseline
treatment effect of the income group 2 ($50-100K) which allows us to
compare the treatment effect among different income levels. First, the
income group 2 received the treatment effect increases deposit amounts
by 587.95 units on average when comparing the income group 2 within the
control group. The income group 1 received the treatment effect saved
41.52 units less than the income group 2 received the treatment effect.
However, this estimate is not statistically significant, meaning that
this difference is not a meaningful difference but just random
variation. However, the income group 3 in the treatment effect saved
437.46 units less than the income 2 group under the treatment effect and
this estimate is statistically significant,concluding that the treatment
effect differs between these groups.</p>
</div>
<div id="c-model-3-including-age-interactions" class="section level4">
<h4>(c) Model 3: Including Age Interactions</h4>
<pre class="r"><code>### Third Model, with Age
OLS&lt;-lm(Savings$Deposits ~ Savings$TreatGroup*Savings$IncGrp + Savings$TreatGroup*Savings$Age35)
summary(OLS)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Savings$Deposits ~ Savings$TreatGroup * Savings$IncGrp + 
##     Savings$TreatGroup * Savings$Age35)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2725.22  -913.01   -17.04   902.40  2853.08 
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                               803.44      48.81  16.461  &lt; 2e-16
## Savings$TreatGroup                        352.64      70.26   5.019 5.36e-07
## Savings$IncGrp&lt;$50K                      -206.15      47.90  -4.303 1.71e-05
## Savings$IncGrp&gt;$100K                      583.82      95.19   6.133 9.29e-10
## Savings$Age35                            1010.01      47.27  21.367  &lt; 2e-16
## Savings$TreatGroup:Savings$IncGrp&lt;$50K    -38.99      68.94  -0.566 0.571681
## Savings$TreatGroup:Savings$IncGrp&gt;$100K  -460.18     132.46  -3.474 0.000517
## Savings$TreatGroup:Savings$Age35          356.44      67.79   5.258 1.52e-07
##                                            
## (Intercept)                             ***
## Savings$TreatGroup                      ***
## Savings$IncGrp&lt;$50K                     ***
## Savings$IncGrp&gt;$100K                    ***
## Savings$Age35                           ***
## Savings$TreatGroup:Savings$IncGrp&lt;$50K     
## Savings$TreatGroup:Savings$IncGrp&gt;$100K ***
## Savings$TreatGroup:Savings$Age35        ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1140 on 4992 degrees of freedom
## Multiple R-squared:  0.2488, Adjusted R-squared:  0.2477 
## F-statistic: 236.1 on 7 and 4992 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretation</strong>: Here in this regression model, Age
and income are covariates to estimate CATEs (Conditional Average
Treatment effects) which can estimate an individual’s heterogeneous
treatment effect. Age is a categorical variable with two different
value, one of which is younger than 35 (&lt;35) and the other one is
older than or equal to 35 (&gt;=35). Intercept 803.44 units represents
people’s average saving amounts in the control group under 35 (&lt;35)
within the income group 2 ($50-100K). The treatment group effect is
352.64 units, indicating that people received treatment effect who are
younger than 35 within the income group 2 saved more deposits (treatment
effect) on average compared to the control group. We can answer the
following questions by combining the effects of covariates such as age
and income and their corresponding interaction terms with the treatment
group and calculate CATE (Conditional Average Treatment Effect).</p>
<ol style="list-style-type: decimal">
<li>What would the treatment effect be for some of age 30 with income of
$40K? The treatment effect is 38.99 units less than the control group
with the same age and within the same income group , which is people
younger than 30 within the income group 1 in the control group, which is
803.44 - 206.15 = 597.29 units. In conclusion, the treatment effect is
558.30 units.</li>
<li>What would the treatment effect be for some of age 30 with income of
$75K? The treatment effect is 325.64 units greater than the control
group with the same age and within the same income group, which is
people younger than 30 within income group2 in the control group, which
is 803.44. In conclusion, the treatment effect is 1129.08 units.</li>
</ol>
</div>
<div id="d-model-4-continuous-income-and-age" class="section level4">
<h4>(d) Model 4: Continuous Income and Age</h4>
<pre class="r"><code>### Fourth model, with continuous interactions
# Appropriate if the treatment effect relationship is linear
OLS&lt;-lm(Savings$Deposits ~ Savings$TreatGroup*Savings$Income + Savings$TreatGroup*Savings$Age)
summary(OLS)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Savings$Deposits ~ Savings$TreatGroup * Savings$Income + 
##     Savings$TreatGroup * Savings$Age)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1988.6  -905.9   -10.7   924.4  2062.0 
## 
## Coefficients:
##                                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                       -1.026e+03  7.630e+01 -13.450  &lt; 2e-16 ***
## Savings$TreatGroup                 3.670e+02  1.075e+02   3.413 0.000647 ***
## Savings$Income                     7.807e-03  6.884e-04  11.340  &lt; 2e-16 ***
## Savings$Age                        4.847e+01  1.545e+00  31.367  &lt; 2e-16 ***
## Savings$TreatGroup:Savings$Income -4.383e-03  9.749e-04  -4.496 7.10e-06 ***
## Savings$TreatGroup:Savings$Age     8.963e+00  2.186e+00   4.101 4.19e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1049 on 4994 degrees of freedom
## Multiple R-squared:  0.3637, Adjusted R-squared:  0.363 
## F-statistic: 570.9 on 5 and 4994 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Interpretation</strong>: In this regression model, covariates
such as income and age are both treated an continuous. In case of the
intercept, it represents people in the control group when their age and
income are both zero saved -1026 units on average but it is not
realistic because in the real world, age and income cannot be zero. When
people in the control group with their age and income being zero are
treated, their savings increases by 367 units on average. When income
increases by 1 unit in the control group, the savings increases by
0.007807 units on average. Similarly, if age increases by 1 unit, the
savings increases by 48.47 units on average. When income increases by 1
unit , the treatment effect decreases by 0.004383 units on average
whereas when age increases by 1 unit, the treatment effect increases by
8.963 units on average.</p>
</div>
</div>
<div id="conclusion-6" class="section level3">
<h3>4. Conclusion</h3>
<ul>
<li>The first model focuses on treatment effects for each income group,
showing significant increases in deposits for Income Groups 1 and
2.</li>
<li>The second model emphasizes comparisons between groups, revealing
significant differences between Income Groups 3 and 2 under
treatment.</li>
<li>The inclusion of age in the third and fourth models highlights the
role of individual-level covariates in explaining treatment
heterogeneity.</li>
<li>Continuous interaction models provide nuanced insights but require
careful interpretation due to extrapolation limitations.</li>
</ul>
</div>
</div>


<br><br>
<footer>
  <p class="copyright text-muted" align="center">Copyright &copy; 2022 John Appleseed</p>
</footer>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4,h5",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
